---
- name: "Add nginx apt key"
  apt_key:
      url: http://nginx.org/keys/nginx_signing.key
      state: present

- name: "Add nginx repository"
  apt_repository:
      repo: "{{ repository }}"
      state: present
      update_cache: true
  with_items:
    - "deb http://nginx.org/packages/ubuntu/ {{ ansible_distribution_release|lower }} nginx"
    - "deb-src http://nginx.org/packages/ubuntu/ {{ ansible_distribution_release|lower }} nginx"
  loop_control:
      loop_var: repository

- name: "Install nginx"
  package:
    name: nginx
    state: present

- name: "Remove Default Site"
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: restart nginx