---
ansible_connection: winrm
ansible_winrm_transport: credssp
ansible_winrm_server_cert_validation: ignore

ansible_become_user: vagrant
ansible_become_pass: vagrant
become_method: runas
become_flags: logon_type=new_credentials logon_flags=netcredentials_only

# Duplicati Configuration
backup_duplicati_backup_paths:
  - "C:\\Users\\{{ ansible_user }}\\Downloads"
  - "C:\\Users\\{{ ansible_user }}\\Documents"
  - "C:\\Users\\{{ ansible_user }}\\AppData"
