---
galaxy_info:
  author: Chris Campbell
  description: Thunderbird Client Setup and Configuration
  company: KLS Air Express, Inc.
  license: GPLv3
  min_ansible_version: 2.5
  platforms:
    - name: Windows
    - name: Debian
