---
# roles/workstation/tasks/csr.yml

- name: 'Installed: .NET 4.5'
  win_chocolatey:
      name: dotnet4.5
      state: present
  notify: reboot windows

- name: 'Install ZaZa Alerter'
  win_package:
      path: "{{ zaza_win_installer }}"
      state: present
      product_id: '{AE911B5B-6516-4CCE-954F-1486FAFDA5AD}'
  when: ansible_winrm_transport == 'credssp'

- name: 'Installed: PC Miler'
  win_copy:
      remote_src: true
      src: '\\kls-dms\dist\install\PC Miler\PMW2000'
      dest: '\'

- name: 'Check: PC Miler Shortcut'
  win_shortcut:
      src: C:\PMW2000\PCMWIN32.EXE
      dest: "C:\\Users\\{{ ansible_user }}\\Desktop\\PCMILER2000.lnk"
      icon: C:\PMW2000\PCMWIN32.EXE,0
      hotkey: Ctrl+Alt+M