---
- name: '.NET'
  include_tasks: "{{ role_path }}/tasks/windows/dotnet.yml"
  vars:
    dotnet_state: present

- name: "Sqlite3"
  include_tasks: "{{ role_path }}/tasks/windows/sqlite3.yml"
  vars:
    sqlite_state: present

- name: "Paths (present)"
  include_tasks: "{{ role_path }}/tasks/windows/paths.yml"
  vars:
    state: present

- name: 'Download Duplicati MSI'
  win_get_url:
    url: "{{ backup_duplicati_msi_url }}"
    dest: "{{ backup_duplicati_msi_path }}"
  notify: remove duplicati msi

- name: 'Duplicati (present)'
  win_package:
    path: "{{ backup_duplicati_msi_path }}"
    state: present

- name: 'Duplicati Service (started)'
  win_service:
    name: duplicati
    path: "{{ backup_duplicati_service_path }}"
    display_name: "Duplicati"
    description: "Service Check for Duplicati Server"
