---
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: Ubuntu-18-Server
    box: ubuntu18
    instance_raw_config_args:
      - "vm.network 'private_network', type: 'static', ip: '192.168.1.11'"
    memory: 2048
    cpus: 2
    groups:
      - linux_workstation
      - linux_server
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    links:
      group_vars: inventory/group_vars
      host_vars: inventory/host_vars
  lint:
    name: ansible-lint
scenario:
  name: default
  create_sequence:
    - create
    - prepare
  check_sequence:
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - prepare
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
verifier:
  name: inspec
  lint:
    name: rubocop
