---
- name: Setting variables
  set_fact:
    inspec_download_url: "https://packages.chef.io/files/stable/inspec/3.0.12/windows/2016/inspec-3.0.12-1-x64.msi"
    inspec_download_sha256sum: 19722a192d16c6bf742df8526fafedc58bd0fcb1e1c7e67b5d1b50141d93cb7c

- name: Download Inspec
  win_get_url:
    url: "{{ inspec_download_url }}"
    dest: "{{ inspec_download_source_dir }}"

- name: Checksum Inspec Download
  win_stat:
    path: "{{ inspec_download_source_dir }}\\{{ inspec_download_url.split('/')[-1] }}"
    get_checksum: true
    checksum_algorithm: sha256
  register: download_sha256sum_actual

- name: Fail on Incorrect Checksum
  fail:
    msg: "Download checksum does not match expected"
  when: download_sha256sum_actual.stat.checksum != inspec_download_sha256sum

- name: Install Inspec
  win_package:
    path: "{{ inspec_download_source_dir }}\\{{ inspec_download_url.split('/')[-1] }}"
    product_id: "C36AC954-C4C1-4C17-9783-29EE1DB5DBDB"
    state: present

- name: Create Molecule directory for test files
  win_file:
    path: "{{ inspec_test_directory }}"
    state: directory

- name: Copy Inspec tests to remote
  win_copy:
    src: "{{ item }}"
    dest: "{{ inspec_test_directory }}/{{ item | basename }}"
  with_fileglob:
    - "{{ lookup('env', 'MOLECULE_VERIFIER_TEST_DIRECTORY') }}/windows/test_*.rb"

- name: Register test files
  win_find:
    paths: "{{ inspec_test_directory }}"
    patterns: "test_*.rb"
  register: tests

- name: Execute Inspec tests
  win_command: "{{ inspec_bin }} exec {{ item.path }}"
  register: test_results
  loop: "{{ tests.files }}"
  ignore_errors: true

- name: Display details about the Inspec results
  debug:
    msg: "{{ item.stdout_lines }}"
  loop: "{{ test_results.results }}"

- name: Fail when tests fail
  fail:
    msg: "Inspec failed to validate"
  when: item.rc != 0
  loop: "{{ test_results.results }}"
