---
- name: reboot windows
  win_reboot:
  register: reset
  when: ansible_reboot_pending
  failed_when: reset is failed and 'A system shutdown has already been scheduled.' not in reset.msg

- name: remove scripts
  win_file:
      path: "\\Users\\{{ ansible_user }}\\Downloads\\{{ item }}"
      state: absent
  loop:
      - PrivatizeNetworks.ps1
      - ConfigureNetworkInterfaces.ps1
